const SET_PRODUCTS = "SET_PRODUCTS"
const ADD_PRODUCT = "ADD_PRODUCT"
const DELETE_PRODUCT = "DELETE_PRODUCT"
const SET_LOADING = "SET_LOADING"
const SET_ERROR = "SET_ERROR"

export { ADD_PRODUCT, DELETE_PRODUCT, SET_ERROR, SET_LOADING, SET_PRODUCTS }